### ISSUE TITLE
S7 - After factory reset, No longer detecting disconnection from devices.

### ISSUE THREAD

**Issue by jkunst830** [jroal/a2dpvolume#268]
After a factory reset, the notifications are not working as they were before.

When set to display notifications when connected...
Works as expected until I disconnected the device or power. The notification remains showing connected. Inside the app, the "**" shows on the connection that the phone was previously connected to. Stopping and restarting the service within the app fixes the notification, but the app crashes on exit.

Changing the notification setting to never show notification seems to have no effect. I get the same behavior as described above. 
Phone - S7
Android version 8.0.0

**Comment by uschindler** [comment]
With the latest update I cannot disable notifications anymore - this is a new bug. But you can do this on the operating system side (disable all notifications by A2DPVolume).

On the S7 there is also the problem that it sometimes fails to get the GPC location. The service is running (it adjusts volume,...), but it does not record the GPS location successfully after disconnect. Sometimes it works, sometimes not.

**Comment by jkunst830** [comment]
Thank you. With playing around more, I believe there is something else going on. It doesn't seem to detect when I disconnect from a device. I can disconnect it from Bluetooth or power and it never resets the volume changes like it used to. For example, on power connection, I have it silence notifications - When I disconnect power, it doesn't restore the volume. I think that's why it also keeps the ** indication in the app after disconnect.

**Comment by uschindler** [comment]
On the S7 you should put A2DP volume on the list of apps that should never be energy-saved. The S7 and later Samsung phones are very aggressive in killing apps. You can only prevent this by putting ist on the list of apps to not "hibernate". There are 2 places in setting where you need to do this.

**Comment by uschindler** [comment]
https://www.androidexplained.com/galaxy-s7-disable-doze/

**Comment by jkunst830** [comment]
Thanks for your help. I did forget about this feature. I think I have a newer version of Android and don't have any feature named doze or hibernate. I did add A2DP to the list of unmonitored apps in the battery setting so it would not be put to sleep.

This did not help however. A2DP is still not detecting when I disconnect a device. You mention 2 places in the settings, but I couldn't find any other setting that may be putting the app to sleep.

**Comment by uschindler** [comment]
Sorry, it's in German only, but this is the not so obvious setting:

![20181118_193701](https://user-images.githubusercontent.com/1005388/48676647-dd32fd80-eb69-11e8-8b60-ca8d631e9275.jpg)
![20181118_193727](https://user-images.githubusercontent.com/1005388/48676648-e623cf00-eb69-11e8-868e-21172878986d.jpg)
![20181118_193751](https://user-images.githubusercontent.com/1005388/48676651-eae88300-eb69-11e8-9714-80c744f02869.jpg)

**Comment by jkunst830** [comment]
Thanks again. I found the setting, and disabled it for A2DP. Didn't seen to help the issue though. I even restarted to check.

**Comment by uschindler** [comment]
Then it's strange. I also use S7 with latest firmware. No problems.

**Comment by jroal** [comment]
Make sure you have given the app all permissions.  I did not spend the time to carefully check permissions in all use cases.  Go into Android settings -> Apps & notifications -> App info -> A2Dp Volume -. Permissions.  Make sure all permissions are given or the app my crash or misbehave.

**Comment by jkunst830** [comment]
Thanks jroal, that was actually something I did before I opened the issue. All permissions available are given. Contacts, Location, Phone, SMS, Storage.

I'm stumped since I never had a problem with the app on this phone before the reset.

**Comment by jroal** [comment]
Can you try uninstalling and reinstalling?

**Comment by jroal** [comment]
I pushed a beta today with a bunch of fixes, many relating to notifications. You can get it by becoming a beta tester by following this link https://play.google.com/apps/testing/a2dp.Vol

**Comment by jkunst830** [comment]
Thanks Jim.
The uninstall/reinstall didn't work. I was planning on trying it again without customizing any settings in the app to see if that had a different result.

The beta link didn't work for me.
 "App not available for this account
Your account isn't currently eligible for this app's testing program."

Do I need to register my account?
I appreciate everything you do for this app. It really is great.

**Comment by jroal** [comment]
If you don't want to wait for the Play Store to push the beta, you can [download it here.](https://1drv.ms/f/s!AgUbpiol3wYLux6pg4EQ-ee8sGci).  Install A2DPVolume2.12.10.5e.apk.  I post this for people who cannot access the Play Store mostly but it is also handy for times like this.

**Comment by jkunst830** [comment]
Grabbed 2.12.10.5 from Google Play, but it seems to have the same issue. I'll keep playing with it when I get the chance. Maybe uninstall and install the apk.

**Comment by jroal** [comment]
I have pushed several updates since 2.12.10.5 now.  Do you still have the issue?  As we could not duplicate it I did not necessarily make a fix for this but I did make several fixes to prevent crashing at various points which may be related.  Also, if you have the latest as of today and you still have the issue, have you tried uninstalling and reinstalling?

**Comment by jkunst830** [comment]
Thanks for following up. - Still no luck for me though.

I actually uninstalled it a couple of weeks ago because the service would start after any update. As soon as it updated, it thought it would connected to the power and implemented the auto settings.

I just tried installing it again from the play store (beta). It seemed to respond to the power connection, but again did not detect when I disconnected it from power. If I manually stop the service, the icon goes away, but the settings do not revert (no surprise). If I then manually restart the service, it immediately thinks its connected to power. The icon displayed is actually different than the one in my settings. It seems to show the A2DP icon in the notifications even though I do not have this selected for any service. I gave my phone a restart, and get the same behavior.

Version 2.12.11.1

**Comment by jroal** [comment]
See issue [277](https://github.com/jroal/a2dpvolume/issues/277).  I just pushed 2.12.11.8 to beta.  We tested on a friends Pixel 2 that was having this issue as well and it now works correctly.

**Comment by jroal** [comment]
I am closing this with 2.12.11.8.  If the issue happens, we can re-open it or launch a new issue.

**Comment by jkunst830** [comment]
Uninstalled and reinstalled 2.12.11.8 and I am seeing the same issue. I place my phone on a wireless charger and leave it for a min. When I remove the phone, the icon remains and the app still shows ** next to the power connection.

At this point, no need to reopen, I'm planning on getting a new phone soon.
Thank you for  your efforts.
